---
# tasks file for gettemp

- name: get_python_pip3
  apt: 
    name: python3-pip
    state: latest

- name: copy_python
  copy: 
    src: gettemp.py
    dest: /opt/gettemp.py
    owner: "{{ ansible_user }}"
    mode: 0744

- name: copy_config
  template:
    src: gettemp.service.j2
    dest: /lib/systemd/system/gettemp.service
    owner: "{{ ansible_user }}"
    mode: 0644

- name: install_requirements
  pip:  
    name: "{{ item }}"
    executable: /usr/bin/pip3
    state: latest
  with_items:
    - setuptools
    - prometheus-client
    - adafruit-blinka # contains board and sub-packages needed
    - cython
    - rpi.gpio
    - Adafruit_DHT
      
- name: enable_service
  systemd:
    name: gettemp.service
    daemon_reload: yes
    state: restarted
    enabled: yes

