---

# - name: set_time
#   become: yes
#   command: hwclock --hctosys 

- name: set_time_zone
  timezone: 
    name: America/Chicago

#- name: remove_unatt_upgrade
#  apt:
#    name: unattended-upgrades
#    state: absent

- name: remove_dpkg
  command: mv /var/lib/dpkg/lock /var/lib/dpkg/lock.bak

- name: get_gpg
  apt_key:
    url: https://packages.grafana.com/gpg.key

- name: repo_for_updates
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: update_cache
  become: yes
  apt:
    update_cache: yes

#- name: remove_dpkg
#  command: mv /var/lib/dpkg/lock /var/lib/dpkg/lock.bak

#- name: remove_dpkg
#  file: 
#    state: absent
#    path: "/var/lib/dpkg/lock"
  
#- name: wait
#  become: yes
#  wait_for: 
#    path: /var/lib/dpkg/lock-frontend 
#    state: absent

- name: download_grafana
  apt:
    name: grafana
    state: latest
    #register: apt_status
    #until: apt_status is success

- name: copy_ini
  copy:
    src: grafana.ini
    dest: /etc/grafana/grafana.ini
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: restart_service
  service: 
    name: grafana-server.service
    state: restarted
